name: Lint, Test & Deploy Project
on: [push]
jobs:
  lint_job:
    runs-on: ubuntu-latest
    - name: Get Code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install depedencies
      run: npm ci
    - name: Run Lint code
      run: npm lint
    - name: Lint code
      run: echo "Lint code"
  test_job:
    needs: [lint_job]
    runs-on: ubuntu-latest
    - name: Get Code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install depedencies
      run: npm ci
    - name: Run Test Job
      run: npm test
    - name: Test job
      run: echo "Test code"
  deploy_job:
    needs: [test_job]
    runs-on: ubuntu-latest
    - name: Get Code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install depedencies
      run: npm ci
    - name: Build code
      run: npm run build
    - name: Deploy job
      run: echo "Deploy Job"
